sudo: required
services:
  - docker

before_install:
  - docker build -t bhhan87/docker-react .

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-ap-northeast-2-852093670342
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY